@startuml
autonumber
hide footbox

actor "Human Resource Representative" as HRR

participant ":System" as SYST

activate HRR

HRR-> SYST : Iniciates the request to specify a collaborator
activate SYST
SYST --> HRR: Request all information needed (i.e. email, first name,\n last name and complete name,mechanographic number, \naddress, phone code, phone number, birth date)
deactivate SYST

HRR-> SYST : Inserts the requested information
activate SYST
loop until there is no more roles to add
SYST --> HRR: Shows role's list
deactivate SYST

HRR-> SYST : Select the intended role
activate SYST

SYST --> HRR: Asks if the user wants to add more roles
deactivate SYST

HRR-> SYST : Responds
activate SYST
end

SYST --> HRR: Shows colaborator's list
deactivate SYST

HRR-> SYST : Select his/hers manager
activate SYST
SYST --> HRR: Validates, presents the information and asks for confirmation
deactivate SYST

HRR-> SYST : Confirms
activate SYST
SYST --> HRR: Informs of the success of the operation
deactivate SYST

deactivate HRR

@enduml