@startuml
skinparam classAttributeIconSize 0

package "Presentation" #DDDDDD {
    class ConsultAssignedPendingTasksUI<<presentation>>{
    }
}


package "Application" #DDDDDD {
    class ConsultAssignedPendingTasksController<<application>>{
        + create()
        + getTasksOfCollaborator(collaborator)
        + getTasksOfCollaboratorByPriority(collaborator, priority)
        + getTasksOfCollaboratorBeforeFinishDate(collaborator, finishDate)
    }

    class OrderAssignedPendingTasksController<<application>>{
        + create()
        + orderTasksOfCollaboratorByPriority(tasks)
        + orderTasksOfCollaboratorByReversePriority(tasks)
        + orderTasksOfCollaboratorByReverseFinishDate(tasks)
    }
}


package "Domain" #DDDDDD {

    abstract class Task<<Entity>><<Root>>{
        - taskDescription
        - taskStatus
        - taskPriority
        - taskResult
        - collaborator
        +create(taskDescription, taskPriority)
        +assignCollaborator(collaborator)
    }

    class ManualTask<<Entity>>{
        - form
        - limitDate
        +create(taskDescription, taskPriority, limitDate, form)
    }

    class Collaborator<<Entity>><<Root>>{
        - mecanographicNumber
        - systemUser
        - manager
        - phoneNumber
        - birthDate
        - address
        - completeName
        - shortName
        - teams
        + create(systemUser, manager, phoneNumber, birthDate, address, completeName, shortName, mecanographicNumber)
        + addTeam(team)
        + removeTeam(team)
    }

    class Form<<Entity>><<Root>> {
        - name
        - formType
        - attributeList
        + create(name, formType, attributeList)
    }
}

package Persistence #DDDDDD {
    class PersistenceContext<<persistence>>{
        +repositories()
    }

    class AppSettings<<persistence>>{
        +instance()
        +getRepositoryFactory()
    }

    package Factory #DDDDDD {
        class RepositoryFactory<<factory>>{
            +create()
            +collaborators()
            +tasks()
            +teams()
            +forms()
    }
}

package "Repository" #DDDDDD {
    class TaskRepository<<repository>>{
        +create()
        +findAll()
        +save(Task)
    }

    interface TaskRepositoryInterface{

    }
}


ConsultAssignedPendingTasksUI ..> ConsultAssignedPendingTasksController
ConsultAssignedPendingTasksUI ..> OrderAssignedPendingTasksController
ConsultAssignedPendingTasksController ..> PersistenceContext

TaskRepository ..> TaskRepositoryInterface

AppSettings -> RepositoryFactory : creates
PersistenceContext -> AppSettings : implements

RepositoryFactory "1" -> "1" TaskRepository : has

TaskRepository "1" -> "*" ManualTask : saves

ManualTask -> Task : extends

Task -> Collaborator : has

ManualTask -> Form : has

@enduml