#!/bin/bash
rm -f server_http.jks
echo -e "$(hostname -f)\nDEI\nISEP\nPORTO\nPORTO\nPT\nyes" | keytool -genkey -v -alias server_http -keyalg RSA -keysize 2048 \
	-validity 365 -keystore server_http.jks -storepass forgotten
####
#keytool -list -v -keystore server_http.jks -storepass forgotten
####
