@startuml
autonumber
hide footbox

participant "<<application>>\nServiceSolicitationService" as SRV
participant "<<domain>>\nResponse" as RS
participant "<<grammar>>\nScriptAlgorithms" as SA
database "<<repository>>\nResponseRepository" as RR
participant "<<persistence>>\nPersistenceContext" as PC
participant "<<persistence>>\nAppSettings" as AS
participant "<<factory>>\nRepositoryFactory" as RF
participant "<<domain>>\nAttribute" as A
participant "<<domain>>\nForm" as F

[o-> SRV : createAndValidateResponse(form, lstAnswer)
activate SRV

SRV -> RS** : res = createResponse(form, lstReponses)

SRV -> SA : executeValidateForm(response, mode)
activate SA

ref over SA
  US-0-1007_SD_ExecuteValidateForm
end ref

SA --> SRV : flag
deactivate SA

alt if the responses are valid after executing the validation script (flag == true)

SRV -> RR : save(res)
activate RR

RR --> SRV : response
deactivate RR

<- SRV : response
deactivate SRV

end

@enduml

