@startuml
autonumber
hide footbox

participant "<<boostrapers>>\nCatalogueSpecificationBootstrapper" as BOOT
participant "<<aplication>>\nCatalogueSpecificationController" as CTRL
participant "<<domain>>\ncatalogue:Catalogue" as CATAL

[o-> BOOT : execute

activate BOOT
BOOT -> CTRL** : create()

BOOT -> BOOT : specifyCatalogue(title, briefDescription,\ncompleteDescription, collabID, teamIDs)

BOOT -> CTRL : getCollaborators(collabID)
activate CTRL
ref over CTRL
Code Sequence similar to US-1-2001_SD
end ref
CTRL --> BOOT : collaborator
deactivate CTRL

BOOT -> CTRL : createCatalog(title, briefDescription, \ncompleteDescription, collab, setTeams)
activate CTRL
ref over CTRL
Code Sequence similar to US-1-2001_SD
end ref
CTRL --> BOOT : catalogue
deactivate CTRL

BOOT -> CTRL : saveCatalogue()
activate CTRL
ref over CTRL
Code Sequence similar to US-1-2001_SD
end ref
CTRL --> BOOT : catalogue
deactivate CTRL
deactivate BOOT

@enduml