


@startuml
autonumber
hide footbox

actor "User" as USER

participant "<<presentation>>\nTaskRealizationUI" as UI


activate USER
USER -> UI : Iniciates the request to accomplish a task

activate UI

UI --> USER: show list of tasks pendants


USER->UI: choose task to accomplish

UI --> USER: Requests confirmation

USER -> UI: confirms
 UI-->USER : accomplish the task
@enduml