@startuml
skinparam classAttributeIconSize 0


package "UI" #DDDDDD {
class EspecificarColaboradorUI{

}
}


package "Application" #DDDDDD {
class EspecificarColaboradorController{
+create()
+addColaborador(nomeCurto, nomeCompleto, numMecan,\nmorada, contacto, dataNascimento)
+getFuncaoList()
+addFuncao(funcao)
+saveColaborador()
}
}


package "Domain" #DDDDDD {
class Colaborador{
+create(nomeCurto, nomeCompleto, numMecan,\nmorada, contacto, dataNascimento,funcao)
}

class NomeCurto {
+createNomeCurto(nomeCurto)
-validate(nomeCurto)
}

class NomeCompleto {
+createNomeCompleto(nomeCompleto)
-validate(nomeCompleto)
}

class NumeroMecanografico {
+createNumeroMecanografico(numeroMecanografico)
-validate(numeroMecanografico)
}

class Morada {
+createMorada(morada)
-validate(morada)
}

class Contacto {
+createContacto(contacto)
-validate(contacto)
}

class DataNascimento {
+createDataNascimento(dataNascimento)
-validate(dataNascimento)
}

class Funcao {
+createFuncao(funcao)
-validate(funcao)
}

package Builder #DDDDDD {
class ColaboradorBuilder{
+create()
+setNomeCompleto(nomeCompleto)
+setNumMecan(numMecan)
+setMorada(morada)
+setContacto(contacto)
+setDataNascimento(dataNascimento)
+setFuncao(funcao)
+createColab()
}
}
}

package Persistence #DDDDDD {
class PersistenceContext{
+repositories()
}

class AppSettings{
+instance()
+getRepositoryFactory()
}

package Factory #DDDDDD {
class RepositoryFactory{
+colaboradores()
+funcoes()
}
}

package "Repository" #DDDDDD {
class ColaboradorRepository{
+create()
+save(colaborador)
}

class FuncaoRepository{
+create()
+save(funcao)
}
}

}


EspecificarColaboradorUI ..> EspecificarColaboradorController
EspecificarColaboradorController ..> ColaboradorBuilder
EspecificarColaboradorController ..> PersistenceContext

AppSettings -> RepositoryFactory : cria
PersistenceContext -> AppSettings : implementa

RepositoryFactory "1" -> "1" ColaboradorRepository : possui
RepositoryFactory "1" -> "1" FuncaoRepository : possui

ColaboradorRepository "1" -> "*" Colaborador : guarda
ColaboradorBuilder "1" -> "*" Colaborador : cria

Colaborador "1" -> "1" NomeCurto : tem
Colaborador "1" -> "1" NomeCompleto : tem
Colaborador "1" -> "1" NumeroMecanografico : é identificado por
Colaborador "1" -> "1" Funcao : tem
Colaborador "1" -> "1" Morada : tem
Colaborador "1" -> "1" Contacto : possui
Colaborador "1" -> "1" DataNascimento : tem

@enduml