@startuml
autonumber
hide footbox

actor "Human Resource Representative" as HRR

participant "<<presentation>>\nCollaboratorSpecificationUI" as UI
participant "<<aplication>>\nCollaboratorSpecificationController" as CTRL
participant "<<builder>>\nCollaboratorBuilder" as CB
participant "<<domain>>\nrole:Role" as ROLE
participant "<<domain>>\ncolab:Collaborator" as COLAB
database "<<repository>>\nCollaboratorRepository" as CR

participant "<<persistence>>\nPersistenceContex" as PC
participant "<<persistence>>\nAppSettings" as AS
participant "<<factory>>\nRepositoryFactory" as RF
participant "<<domain>>\nShortName" as SN
participant "<<domain>>\nCompleteName" as CN
participant "<<domain>>\nMechanographicNumber" as MN
participant "<<domain>>\nRole" as R
participant "<<domain>>\nAddress" as A
participant "<<domain>>\nPhoneNumber" as PN
participant "<<domain>>\nBirthDate" as BD

activate HRR

HRR-> UI : Iniciates the request to specify a collaborator
activate UI

UI-> CTRL** : create()

UI --> HRR: Request all information needed (i.e. short and complete name,\nmechanographic number, address, phone number, birth date)

deactivate UI
HRR-> UI : Inserts the requested information
activate UI
UI-> CTRL : addColaborador(shortName, completeName, mechanographicNumber,\naddress, phoneNumber, birthDate)
activate CTRL

CTRL-> CB** : create()
CTRL-> CB : withShortName(shortName)
activate CB
deactivate CB
CTRL-> CB : withCompleteName(completeName)
activate CB
deactivate CB
CTRL-> CB : withMechanographicNumber(mechanographicNumber)
activate CB
deactivate CB
CTRL-> CB : withAddress(address)
activate CB
deactivate CB
CTRL-> CB : withPhoneNumber(phoneNumber)
activate CB
deactivate CB
CTRL-> CB : withBirthDate(birthDate)
activate CB
deactivate CB
deactivate CB
deactivate CTRL

UI-> CTRL : getRoleList()
activate CTRL

CTRL-> ROLE : values()
activate ROLE

ROLE--> CTRL : rolesList
deactivate ROLE
CTRL--> UI : rolesList
deactivate CTRL

UI --> HRR: Shows roles' list
deactivate UI

HRR-> UI : Select the intended role
activate UI

UI-> CTRL : addRole(role)
activate CTRL
CTRL-> CB : withRole(role)
activate CB
deactivate CB
deactivate CTRL

UI --> HRR: Validates, presents the information and asks for confirmation
deactivate UI

deactivate UI
HRR-> UI : Confirms
activate UI

UI-> CTRL : saveColaborator()
activate CTRL

CTRL-> CB : build()
activate CB
CB-> COLAB** : create(shortName, completeName, mechanographicNumber,\naddress, phoneNumber, birthDate,role)

activate COLAB
COLAB --> CB : collaborator
deactivate COLAB
CB --> CTRL : collaborator
deactivate CB

ref over CTRL
US-1-2051_SD_Repo
end ref

CTRL-> CR : save(collaborator)
activate CR
CR --> CTRL : collaborator
deactivate CR
CTRL --> UI : collaborator
deactivate CTRL

UI --> HRR: Informs of the success of the operation
deactivate UI
deactivate HRR

@enduml