@startuml
autonumber
hide footbox

actor "Gestor de Serviços de Help Desk" as GSH
participant ":System" as SYST

activate GSH

GSH -> SYST : envia um pedido para especificar um servico
activate SYST
SYST -> GSH : solicita a introdução de dados (descrição breve e completa)
deactivate SYST

GSH -> SYST : introduz os dados
activate SYST
SYST -> GSH : pergunta se o serviço requer feedback
deactivate SYST

GSH -> SYST : seleciona se pretende ou não feedback neste serviço
activate SYST

alt caso o serviço requeira feedback

SYST -> GSH : solicita a duração máxima permitida para o feedback
deactivate SYST

GSH -> SYST : introduz a duração máxima
activate SYST
end

SYST -> GSH : mostra a lista de catálogos e solicita a escolha de um catálogo
deactivate SYST

GSH -> SYST : escolhe o catálogo onde será disponibilizado o serviço
activate SYST

loop até não serem precisos mais formulários
SYST -> GSH : solicita a introdução do nome do formulário
deactivate SYST

GSH -> SYST : introduz os dados
activate SYST

SYST -> GSH : apresenta os tipos de formulário disponiveis
deactivate SYST

GSH -> SYST : seleciona o tipo de formulário
activate SYST

loop até não serem precisos mais atributos
SYST -> GSH : solicita a introdução de dados (tipo de dados, regex, descrição, script, label, nome)
deactivate SYST

GSH -> SYST : introduz os dados
activate SYST

SYST -> GSH : pergunta se deseja adicionar mais atributos ao formulário em questão
deactivate SYST

GSH -> SYST : responde se pretende ou não adicionar mais atributos
activate SYST
end

SYST -> GSH : pergunta se deseja adicionar mais formulários ao serviço em questão
deactivate SYST

GSH -> SYST : responde se pretende ou não adicionar mais formulários
activate SYST
end

SYST -> GSH : valida, apresenta os dados do servico e solicita uma confirmação
deactivate SYST

GSH -> SYST : confirma
activate SYST
SYST -> GSH : regista o servico e informa do sucesso da operação
deactivate SYST

deactivate GSH

@enduml